### ISSUE TITLE
8.06.py example

### ISSUE THREAD

**Issue by ghost** [epequeno/ThinkPy-Solutions#1]
I think here might have a return when find(word, letter, index) equals to  -1

```
def count(word, letter):
...
        if find(word, letter, index) != -1:
            count += 1
        else:
            return count
...
```

**Comment by epequeno** [comment]
You are correct, thank you. I've changed it to this:

``` python
def find(letter, word, index):
    while index < len(word):
        if word[index] == letter:
            return index
        index += 1
    return -1


def count(letter, word):
    counter = 0
    index = 0
    while index < len(word):
        result = find(letter, word, index)
        if result == -1:
            return counter
        else:
            counter += 1
        index = result + 1
    return counter

print count("n", "Think Python")
```

I think this version is more direct about what each condition means for the flow of the operation. If the letter we're searching for returns -1 then stop iteration by returning the current counter. Once you've reasoned about the 0 case the rest follows.

I also reversed the order of the arguments as it reads more naturally to me now: count this string from that word.
